name: build-and-test-actions
on: [push, pull_request]
jobs:
  test-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: pip install Lektor
      - run: npm install --global npm@latest
      - run: lektor build -f webpack
